### ISSUE TITLE
Official Docker Image for Cobalt Web Frontend

### ISSUE THREAD

**Issue by dennysubke** [imputnet/cobalt#1095]
### describe the feature you'd like to see

First of all, thanks for the amazing work on Cobalt! The API is working great, but it would be really helpful if the web frontend was also available as an official Docker container. 

**Feature Request:**

1.  Provide an official Docker image for the web frontend on Docker Hub or GitHub Container Registry (`ghcr.io`).
2. Include a `docker-compose.yml` to easily deploy both the API and web frontend together.

**Why?**

- Makes installation and updates much easier.
- Clear separation between backend (API) and frontend.
- Users can start the entire system with a single `docker-compose up -d`.

```
#Example docker-compose.yml Setup:

version: '3.7'

services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      API_URL: ""

  cobalt-web:
    image: ghcr.io/imputnet/cobalt-web:latest  
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      API_URL:  # ->> Connects directly to the API
```

If there's already a plan for this feature, it would be great to know if/when it's coming.
Thanks again for your work! 😊
