### ISSUE TITLE
Can't download videos from YouTube on cobalt.tools

### ISSUE THREAD

**Issue by wukko** [imputnet/cobalt#1356]
youtube seems to have changed something on their side, and the main instance can't access videos anymore. specifically, 90% of requests to googlevideo on both iOS and WEB_EMBEDDED client return 403. some requests do go through, but it's rare.

we're already looking into a way to fix this, and will post and update here and on twitter whenever it happens!

cobalt will show this error as long as this issue is present:

<img width="449" alt="Image" src="https://github.com/user-attachments/assets/26b8aa7d-3e7f-4506-8ed7-2eb221f27d1f" />

please **DON'T** make duplicate issues and don't reply with "me too". it affects everyone on the main instance, including you.

you can follow notifications for this issue here:
<img width="290" alt="Image" src="https://github.com/user-attachments/assets/04d2930c-4f3b-401d-8782-007e81db4c67" />

**Comment by maxcomperatore** [comment]
im shaking and crying rn im devastated fr

edit: bro fix it it's been 81 days ong

**Comment by 2shiraz** [comment]
Apparently, youtube blocked the whole subnet of my proxy servers. i was using ipv6 blocks which is blocked up to /40 ips. i guess changing proxy/cloud providers for me is the solution.

**Comment by regedit-sys** [comment]
i think we SHOULD make duplicate issues and reply with "me too"!
okay, but seriously, google is so annoying sometimes. we need to start a movement

**Comment by Intercity225** [comment]
In the meantime is there any alternatives?

**Comment by wukko** [comment]
> In the meantime is there any alternatives?

https://github.com/yt-dlp/yt-dlp

**Comment by Intercity225** [comment]
Thank you, and hoping it's solved promptly!

**Comment by ledsales** [comment]
> In the meantime is there any alternatives?

I just installed JDownloader 2 as a backup until Cobalt is online, it works fine, interface is a bit meh because it grabs everything, not just the vid, but audio streams, images etc, so you have to turn those off. I also haven't found how to make it stop creating subfolders, even for a single video file. But aside from those issues, which are probably me needing more time to play with the interface, it seems to be a good alternative and very quick to download vids.

**Comment by JoaoFelipe3** [comment]
aw dangit can't download sonic cd soundtrack now can i 😭

**Comment by G1tR4kt** [comment]
> In the meantime is there any alternatives?

Ive been downloading from yt for years with random sites, they ALL stopped working last year, i think you would have to wait until cobalt figures it out, its the only way currently i guess

**Comment by MrCoreyTys** [comment]
This is truly mayhem. I'm sure why YouTube is doing this is to promote YT Premium instead of letting people use other video downloaders like Cobalt, I think that's it.

**Comment by andyfoxmsconfig** [comment]
Cobalt is still down, doesn't work
Also of the alternatives to it, whilst it's having seizure due to Google blocking some APIs is:
[ https://en.loader.to/4/ ]

**Comment by pansy4life** [comment]
Is there any ETA on when this could be fixed?

**Comment by masterconfig** [comment]
Are there any news regarding the project's current state? ;-;

**Comment by dumbmoron** [comment]
> Are there any news regarding the project's current state? ;-;

@andyfoxmsconfig  the project is not dead, everything other than youtube still works. if there were any updates, we would post them here (amongst other places)

**Comment by dumbmoron** [comment]
self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md)

**Comment by MatthewSH** [comment]
> self hosted instances are not affected by this, so if you need it to work urgently you could also host your own instance, we have instructions on how to set it up [here](https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md?rgh-link-date=2025-06-22T18%3A24%3A36.000Z)

This, from my testing, is only true if you're on residential IPs or not flagged IPs. My self-hosted instance is impacted because it requires yt-session-generator and keeps throwing the YouTube login error which it hadn't prior.

**Comment by wukko** [comment]
> keeps throwing the YouTube login error which it hadn't prior

then your ip address probably got blocked by youtube. there’s no way around it aside from using account cookies (not recommended, they also tend to get blocked) or using a different ip address :(

**Comment by rupertgti** [comment]
You could self-hosted a cobalt-api and cobalt-web at this moment, if you have a regional block for example like my case....

I use this easy docker-compose, I reference the sources of this:

```
#https://github.com/imputnet/cobalt/blob/main/docs/examples/docker-compose.example.yml
services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    network_mode: "bridge"
    restart: unless-stopped
    container_name: cobalt-api
    ports:
      - 9000:9000/tcp
      # if you use a reverse proxy (such as nginx),
      # uncomment the next line and remove the one above (9000:9000/tcp):
      # - 127.0.0.1:9000:9000

    environment:
      # replace https://api.url.example/ with your instance's url
      # or else tunneling functionality won't work properly
      API_URL: "http://YOUR_IP:9000"
      # if you want to use cookies for fetching data from services,
      # uncomment the next line & volumes section
      # COOKIE_PATH: "/cookies.json"
      # it's recommended to configure bot protection or api keys if the instance is public,
      # see /docs/protect-an-instance.md for more info
      # see /docs/run-an-instance.md for more variables that you can use here

#custom project:
#https://github.com/imputnet/cobalt/issues/768
#https://github.com/NotNite/cobalt-web-docker

  cobalt-web:
    container_name: cobalt-web
    network_mode: "bridge"
    restart: unless-stopped
    build:
      context: https://github.com/NotNite/cobalt-web-docker.git
      dockerfile: Dockerfile
      additional_contexts:
        cobalt-src: https://github.com/imputnet/cobalt.git

      args:
        WEB_HOST: "http://YOUR_IP:9001/"
        WEB_DEFAULT_API: "http://YOUR_IP:9000/"

    ports:
      - 9001:3000/tcp

```
