### ISSUE TITLE
Error in docker container : please run the setup script to fix this: npm run setup

### ISSUE THREAD

**Issue by guguji666666** [imputnet/cobalt#494]
**bug description**
a clear and concise description of what the bug is.

**reproduction steps**
steps to reproduce the behavior:
1. I build the docker image with your Dockerfile in https://github.com/imputnet/cobalt/blob/current/Dockerfile
2. I use the docker compose yaml below to start the container
```yml
version: '3'

services:
  cobalt:
    image: guguji666/cobalt:v20240515
    ports:
      - "9000:9000"
    restart: always
```

**screenshots**
Got the error in the container
```
cobalt-cobalt-1  | cobalt wasn't configured yet or configuration is invalid.
cobalt-cobalt-1  | please run the setup script to fix this: npm run setup
cobalt-cobalt-1  | cobalt wasn't configured yet or configuration is invalid.
```

![image](https://github.com/imputnet/cobalt/assets/96930989/2bee5f85-4dec-4bf6-9a96-caa0e5c483d8)

I tried to enter the container itself to run the command but failed since the container is restarting. Not sure how to fix it.
The docker image is still in my dockerhub. Please advise, thanks!
