### ISSUE TITLE
Don't know how to use CORS_URL when hosting an instance

### ISSUE THREAD

**Issue by owendswang** [imputnet/cobalt#644]
### bug description
I'm using docker compose to setup self-hosted service. But the cors restriction blocks me from accessing api url even when CORS_URL is set.

### reproduction steps
1. add CORS_URL to docker-compose.yml.
2. 'docker compose up -d'
3. download any url.
4. error in console: 'Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://192.168.1.6:9000/api/json. (Reason: CORS request did not succeed). Status code: (null)'

### screenshots
null

### links
any url

### platform information
- OS: ubuntu server 64bit arm64
- browser: firefox
- version: 7 (7.14.6)

### additional context
My 'docker-compose.yml' file content:
```
services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-api

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9000:9000/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
            #- 127.0.0.1:9000:9000

        environment:
            # replace https://api.cobalt.tools/ with your instance's target url in same format
            API_URL: "http://192.168.1.6:9000/"
            # replace eu-nl with your instance's distinctive name
            API_NAME: "zh-cn"
            # if you want to use cookies when fetching data from services, uncomment the next line and the lines under volume
            COOKIE_PATH: "/cookies.json"
            # see docs/run-an-instance.md for more information
            CORS_URL: "http://192.168.1.6:9001/"
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

        # if you want to use cookies when fetching data from services, uncomment volumes and next line
        volumes:
            - ./cookies.json:/cookies.json

    cobalt-web:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-web

        init: true

        # if container doesn't run detached on your machine, uncomment the next line
        #tty: true

        ports:
            - 9001:9001/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9001:9001/tcp):
            #- 127.0.0.1:9001:9001

        environment:
            # replace https://cobalt.tools/ with your instance's target url in same format
            WEB_URL: "http://192.168.1.6:9001/"
            # replace https://api.cobalt.tools/ with preferred api instance url
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    # update the cobalt image automatically with watchtower
    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```
