### ISSUE TITLE
Cannot use Cobalt API locally with invalid certificates

### ISSUE THREAD

**Issue by ToshY** [imputnet/cobalt#659]
### bug description

Running Cobalt locally, both web and API, without valid certificates, fails when making API request from the web UI.

### reproduction steps

1. Create `.env` and  `compose.yaml`.

<details><summary><code>.env</code></summary>

```dotenv
COBALT_IMAGE_VERSION="7.15"
APP_DOMAIN="test.local"
COBALT_WEB_URL="dl.${APP_DOMAIN}"
COBALT_API_URL="dl-api.${APP_DOMAIN}"
```

</details>

<details><summary><code>compose.yaml</code></summary>

```yaml
services:
  cobalt-web:
    image: ghcr.io/imputnet/cobalt:${COBALT_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - 9001:${COBALT_WEB_PORT:-9001}
    environment:
      WEB_URL: ${COBALT_WEB_SCHEME:-https}://${COBALT_WEB_URL:?}/
      WEB_PORT: ${COBALT_WEB_PORT:-9001}
      API_URL: ${COBALT_API_SCHEME:-https}://${COBALT_API_URL:?}/
      SHOW_SPONSORS: ${COBALT_SHOW_SPONSORS:-0}
      IS_BETA: ${COBALT_IS_BETA:-0}
      PLAUSIBLE_HOSTNAME: ${PLAUSIBLE_HOSTNAME:-}
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.cobalt-web.tls: true
      traefik.http.routers.cobalt-web.entrypoints: websecure
      traefik.http.routers.cobalt-web.rule: Host(`${COBALT_WEB_URL}`)
      traefik.http.routers.cobalt-web.service: cobalt-web
      traefik.http.services.cobalt-web.loadbalancer.server.port: ${COBALT_WEB_PORT:-9001}
    networks:
      - cobalt
      - proxy

  cobalt-api:
    image: ghcr.io/imputnet/cobalt:${COBALT_IMAGE_VERSION}
    restart: unless-stopped
    ports:
      - 9000:${COBALT_API_PORT:-9000}
    environment:
      API_URL: ${COBALT_API_SCHEME:-https}://${COBALT_API_URL:?}/
      API_PORT: ${COBALT_API_PORT:-9000}
      API_LISTEN_ADDRESS: ${COBALT_API_LISTEN_ADDRESS:-0.0.0.0}
      API_NAME: ${COBALT_API_NAME:-unknown}
      API_EXTERNAL_PROXY: ${COBALT_API_EXTERNAL_PROXY:-}
      CORS_WILDCARD: ${COBALT_CORS_WILDCARD:-1}
      CORS_URL: ${COBALT_CORS_URL:-}
      COOKIE_PATH: ${COBALT_COOKIE_PATH:-}
      PROCESSING_PRIORITY: ${COBALT_PROCESSING_PRIORITY:-}
      FREEBIND_CIDR: ${COBALT_FREEBIND_CIDR:-}
      RATELIMIT_WINDOW: ${COBALT_RATELIMIT_WINDOW:-60}
      RATELIMIT_MAX: ${COBALT_RATELIMIT_MAX:-20}
      DURATION_LIMIT: ${COBALT_DURATION_LIMIT:-10800}
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.cobalt-api.tls: true
      traefik.http.routers.cobalt-api.entrypoints: websecure
      traefik.http.routers.cobalt-api.rule: Host(`${COBALT_API_URL}`)
      traefik.http.routers.cobalt-api.service: cobalt-api
      traefik.http.services.cobalt-api.loadbalancer.server.port: ${COBALT_API_PORT:-9000}
    networks:
      - cobalt
      - proxy

networks:
  cobalt:
    driver: bridge
  proxy:
    external: true
```

</details> 

2. Up stack

```shell
$ docker compose pull
$ docker compose up  -d --build --force-recreate --remove-orphans
```

3. Check UI and test a (random) URL.

Gives network error regarding invalid certificate.

### screenshots

![image](https://github.com/user-attachments/assets/2cfe1068-24e5-4435-a6d0-e8a4f5cc44ee)

![image](https://github.com/user-attachments/assets/f0b11c34-722c-418f-9ba4-5ab60b56f6fd)

### platform information
- OS: `windows`
- browser: `chrome`
- version: `127.0.6533.72`

### additional context

possible solution might be create a custom environment variable and create an agent that would allow `rejectUnauthorized: false`: https://github.com/orgs/nodejs/discussions/44038#discussioncomment-5701073
