### ISSUE TITLE
Empty file downloaded from youtube by selfhosted cobalt

### ISSUE THREAD

**Issue by FixFever** [imputnet/cobalt#711]
### bug description
cobalt.tools successfully downloads videos from YouTube. But selfhosted solution downloads an empty file for any video from YouTube.

### reproduction steps
docker-compose:
```
  cobalt_api:
    image: ghcr.io/imputnet/cobalt:latest
    container_name: cobalt_api
    ports:
      - 9002:9000/tcp
    environment:
      - API_URL=https://api.cobalt.${DOMAIN}/
      - RATELIMIT_WINDOW=21600
      - RATELIMIT_MAX=1000
      - DURATION_LIMIT=21600
      
  cobalt:
    image: ghcr.io/imputnet/cobalt:latest
    container_name: cobalt
    ports:
      - 9003:9001/tcp
    environment:
      - WEB_URL=https://cobalt.${DOMAIN}/
      - API_URL=https://api.cobalt.${DOMAIN}/
```
All quality and codec settings are similar to those in cobalt.tools.
Version similar: v.7.15-05ba1f0 (current)
Trying download any video from youtube from cobalt.tools and selfhosted app.

### screenshots
![Screenshot_13](https://github.com/user-attachments/assets/00f2a8af-8f4b-4ca1-864c-5f67fa4619e3)
