### ISSUE TITLE
does cobalt api support change port?

### ISSUE THREAD

**Issue by Yumega** [imputnet/cobalt#796]
### problem description

 I changed the port into 9002, it doesn't work. 
port 9000 has used by protainer, must change the port.
  ```
services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:7
        network_mode: bridge
        restart: unless-stopped
        container_name: cobalt-api
        init: true
        tty: true
        ports:
            - 9002:9002/tcp
        environment:
            API_URL: "http://192.168.11.1:9002/"
            API_NAME: "cobalt-api"
   ```
